"""
This file stores the database tables as dictionaries
The keys refer to the original variables (Spanish), the values refer to the names that will be used in the SQL database (English)
"""

identifiers_dict = {
    "ID": "id",   
    "CD_PET": "cd_pet",        
    }

diagnostic_dict = {
    "ID": "id",   
    "DiagnosticoClinico": "diagnostic"
    }
    
demographic_dict = {
    "ID": "id",  
    "Sexo": "sex",
    "Edadactual": "current_age",
    "Edadinicio": "starting_age",
    "AñosEducacion": "education_years",
    "LeiayEscribia": "read_and_write"
    }
    
dates_dict = {
    "ID": "id",
    "Fnacimiento": "birth_date",
    "FechaPET": "pet_date",
    "FechaVisita": "visit_date"
    }
    
screening_dict = {
    "ID": "id",
    "MMSE": "mmse",
    "Addensbrook": "ace",
    "ACE3total": "ace3_total",
    "ACE3Atencion": "ace3_attention",
    "ACE3Memoria": "ace3_memory",
    "ACE3Fluencia": "ace3_fluency",
    "ACE3Lenguaje": "ace3_language",
    "ACE3Visuoespacial": "ace3_visuospatial"
    }
    
specific_raw_dict = {
    "ID": "id",
    "SpandirBRUTA": "mst_direct",
    "SpanvindirBRUTA": "mst_indirect",                 
    "CorsidirBRUTA": "cbtt_direct",
    "CorsiindirBRUTA": "cbtt_indirect",
    "TMTaBRUTA": "tmt_a",
    "TMTbBRUTA": "tmt_b",
    "SDMTBRUTA": "sdmt",
    "BostonNTBRUTA": "bnt",
    "FCSRTL1bruta": "fcsrt_l1",                      
    "FCSRTLTbruta": "fcsrt_lt",                      
    "FCSRTtotalBRUTA": "fcsrt_total",                
    "FCSRTdifLiBRUTA": "fcsrt_dif_free",             
    "FCSRTdifTBRUTA": "fcsrt_dif_total",             
    "Stroop1BRUTA": "st_1",
    "Stroop2BRUTA": "st_2",
    "Stroop3BRUTA": "st_3",
    "ToltotalcorrecBRUTA": "tlt_total_correct",
    "ToLmovtotalBRUTA": "tlt_total_movements",
    "ToLinicioBRUTA": "tlt_start",
    "ToLejecucBRUTA": "tlt_execution",
    "ToLresolucBRUTA": "tlt_resolution",
    "VOSPdecisBRUTA": "vospt_decision",
    "VOSPsiluetproBRUTA": "vospt_silhouette",
    "VOSPdiscrimBRUTA": "vospt_discrimination",
    "VOSPlocalizBRUTA": "vospt_location",
    "JLObruta": "jlot",
    "FluenciaFormalp": "ft_formal",
    "FluenciaSemanticaAnimales": "ft_animals",
    "ReyCopiaBRUTA": "rocf_copy",
    "Rey3minBRUTA": "rocf_3min",
    "Rey30minBRUTA": "rocf_30min",
    "ReyTiempBRUTA": "rocf_time",
    "ReyReconocBRUTA": "rocf_recognition",
    "ReyTipoCopia": "rocf_type_copy",      
    "Tipo3min": "rocf_type_3min",                         
    "Tipo30min": "rocf_type_30min",
    "PrConstbasicTB": "pctb"
    }
    
specific_corrected_dict = {
    "ID": "id",
    "Spandirecto": "mst_direct",
    "Spanindirecto": "mst_indirect",
    "Corsidirecto": "cbtt_direct",                 
    "Corsiinverso": "cbtt_indirect",               
    "TMTa": "tmt_a",
    "TMTb": "tmt_b",
    "SDMT": "sdmt",
    "BostonNT": "bnt",
    "FCSRTL1": "fcsrt_l1",                           
    "FCSRTLT": "fcsrt_lt",                           
    "FCSRTtotal": "fcsrt_total",                     
    "FCSRTdifLibre": "fcsrt_dif_free",               
    "FCSRTdifTOTAL": "fcsrt_dif_total",              
    "Stroop1": "st_1",
    "Stroop2": "st_2",
    "Stroop3": "st_3",
    "ToLtotalcorrectos": "tlt_total_correct",
    "ToLmovtotales": "tlt_total_movements",
    "ToLinicio": "tlt_start",
    "ToLejecucion": "tlt_execution",
    "ToLresolucion": "tlt_resolution",
    "VOSPdecision": "vospt_decision",
    "VOSPsiluetas": "vospt_silhouette",
    "VOSPdiscriposi": "vospt_discrimination",
    "VOSPlocaliznumero": "vospt_location",
    "JLOescalar": "jlot",
    "FluenciaPescalar": "ft_formal",
    "Fluenciaanimalesescalar": "ft_animals", 
    "ReyCopia": "rocf_copy",
    "Rey3min": "rocf_3min",
    "Rey30min": "rocf_30min",
    "ReyTiempo": "rocf_time",
    "ReyReconocimiento": "rocf_recognition"
    }

aal_quantitative_dict = {
    "ID": "id",
	#Central region
    "precentral_i": "pre_l",
    "precentral_d": "pre_r",
    "postcentral_i": "post_l",                    
    "postcentral_d": "post_r",
    "opercroland_i": "ro_l",                         
    "opercroland_d": "ro_r",
	#Frontal lobe (Lateral surface)
    "frontalsup_i": "f1_l",
    "frontalsup_d": "f1_r",
    "frontalmedio_i": "f2_l",
    "frontalmedio_d": "f2_r",
    "frontalinferoper_i": "f3op_l",
    "frontalinferoper_d": "f3op_r",
    "frontalinftri_i": "f3t_l",
    "frontalinftri_d": "f3t_r",
	#Frontal lobe (Medial surface)
    "frontalsupmed_i": "f1m_l",
    "frontalsupmed_d": "f1m_r",
    "motorsuple_i": "sma_l",                         
    "motorsuple_d": "sma_r",
    "paracentral_i": "pcl_l",                    
    "paracentral_d": "pcl_r",
	#Frontal lobe (Orbital surface)
    "frontalsuporb_i": "f1o_l",
    "frontalsuporb_d": "f1o_r",
    "frontalmedorb_ii": "f1mo_l",
    "frontalmedorb_dd": "f1mo_r",
    "frontalmedioorb_i": "f2o_l",
    "frontalmedioorb_d": "f2o_r",
    "frontalinforb_i": "f3o_l",
    "frontalinforb_d": "f3o_r",
    "recto_i": "gr_l",                        
    "recto_d": "gr_r",                      
    "olf_i": "oc_l",
    "olf_d": "oc_r",
	#Temporal lobe (Lateral surface)
    "tempsuper_i": "t1_l",
    "tempsuper_d": "t1_r",
    "heschl_i": "hes_l",                              
    "heschl_d": "hes_r",
    "temporalmed_i": "t2_l",
    "temporalmed_d": "t2_r",
    "tempinf_i": "t3_l", 
    "tempinf_d": "t3_r",
	#Parietal lobe (Lateral surface)
    "parietalsup_i": "p1_l",
    "parietalsup_d": "p1_r",
    "parietalinf_i": "p2_l",
    "parietalinf_d": "p2_r",
    "angular_i": "ag_l",                            
    "angular_d": "ag_r",
    "supramarginal_i": "smg_l",                
    "supramarginal_d": "smg_r",
	#Parietal lobe (Medial surface)
    "precuneus_i": "pq_l",                
    "precuneus_d": "pq_r",
	#Occipital lobe - Lateral surface
    "occipsup_i": "o1_l",
    "occipsup_d": "o1_r",
    "occipmed_i": "o2_l", 
    "occipmed_d": "o2_r",
    "occipinf_i": "o3_l",
    "occipinf_d": "o3_r",
	#Occipital lobe (Medial and inferior surfaces)
    "cuneus_i": "q_l",
    "cuneus_d": "q_r",
    "calcarino_i": "v1_l",
    "calcarino_d": "v1_r",
    "lingual_i": "ling_l",
    "lingual_d": "ling_r",
    "fusiforme_i": "fusi_l",
    "fusiforme_d": "fusi_r",
	#Limbic lobe
    "polotempsup_i": "t1p_l",         
    "polotempsup_d": "t1p_r",         
    "polotempmed_i": "t2p_l",           
    "polotempmed_d": "t2p_r",	
    "cinguant_i": "acin_l",
    "cinguant_d": "acin_r",
    "cingumed_i": "mcin_l",
    "cingumed_d": "mcin_r",
    "cingupost_i": "pcin_l",
    "cingupost_d": "pcin_r",
    "hipocampo_i": "hip_l",
    "hipocampo_d": "hip_r",
    "parahipocampo_i": "phip_l",
    "parahipocampo_d": "phip_r",	
    "insula_i": "in_l",
    "insula_d": "in_r",
	#Subcortical gray nuclei
    "amigdala_i": "amyg_l",
    "amigdala_d": "amyg_r",  
    "caudado_i": "cau_l",
    "caudado_d": "cau_r",
    "putamen_i": "put_l",
    "putamen_d": "put_r",
    "palido_i": "pal_l",                            
    "palido_d": "pal_r",                             
    "talamo_i": "tha_l",
    "talamo_d": "tha_r"
    }
	
aal_qualitative_dict = {
    "ID": "id",
	#Central region
    "precentral_i_c": "pre_l",
    "precentral_d_c": "pre_r",
    "postcentral_i_c": "post_l",                    
    "postcentral_d_c": "post_r",
    "opercroland_i_c": "ro_l",                         
    "opercroland_d_c": "ro_r",
	#Frontal lobe (Lateral surface)
    "frontalsup_i_c": "f1_l",
    "frontalsup_d_c": "f1_r",
    "frontalmedio_i_c": "f2_l",
    "frontalmedio_d_c": "f2_r",
    "frontalinferoper_i_c": "f3op_l",
    "frontalinferoper_d_c": "f3op_r",
    "frontalinftri_i_c": "f3t_l",
    "frontalinftri_d_c": "f3t_r",
	#Frontal lobe (Medial surface)
    "frontalsupmed_i_c": "f1m_l",
    "frontalsupmed_d_c": "f1m_r",
    "motorsuple_i_c": "sma_l",                         
    "motorsuple_d_c": "sma_r",
    "paracentral_i_c": "pcl_l",                    
    "paracentral_d_c": "pcl_r",
	#Frontal lobe (Orbital surface)
    "frontalsuporb_i_c": "f1o_l",
    "frontalsuporb_d_c": "f1o_r",
    "frontalmedorb_iiii_c": "f1mo_l",
    "frontalmedorb_ddd_c": "f1mo_r",
    "frontalmedioorb_i_c": "f2o_l",
    "frontalmedioorb_d_c": "f2o_r",
    "frontalinforb_i_c": "f3o_l",
    "frontalinforb_d_c": "f3o_r",
    "recto_i_c": "gr_l",                        
    "recto_d_c": "gr_r",                      
    "olf_i_c": "oc_l",
    "olf_d_c": "oc_r",
	#Temporal lobe (Lateral surface)
    "tempsuper_i_c": "t1_l",
    "tempsuper_d_c": "t1_r",
    "heschl_i_c": "hes_l",                              
    "heschl_d_c": "hes_r",
    "temporalmed_i_c": "t2_l",
    "temporalmed_d_c": "t2_r",
    "tempinf_i_c": "t3_l", 
    "tempinf_d_c": "t3_r",
	#Parietal lobe (Lateral surface)
    "parietalsup_i_c": "p1_l",
    "parietalsup_d_c": "p1_r",
    "parietalinf_i_c": "p2_l",
    "parietalinf_d_c": "p2_r",
    "angular_i_c": "ag_l",                            
    "angular_d_c": "ag_r",
    "supramarginal_i_c": "smg_l",                
    "supramarginal_d_c": "smg_r",
	#Parietal lobe (Medial surface)
    "precuneus_i_c": "pq_l",                
    "precuneus_d_c": "pq_r",
	#Occipital lobe - Lateral surface
    "occipsup_i_c": "o1_l",
    "occipsup_d_c": "o1_r",
    "occipmed_i_c": "o2_l", 
    "occipmed_d_c": "o2_r",
    "occipinf_i_c": "o3_l",
    "occipinf_d_c": "o3_r",
	#Occipital lobe (Medial and inferior surfaces)
    "cuneus_i_c": "q_l",
    "cuneus_d_c": "q_r",
    "calcarino_i_c": "v1_l",
    "calcarino_d_c": "v1_r",
    "lingual_i_c": "ling_l",
    "lingual_d_c": "ling_r",
    "fusiforme_i_c": "fusi_l",
    "fusiforme_d_c": "fusi_r",
	#Limbic lobe
    "polotempsup_i_c": "t1p_l",         
    "polotempsup_d_c": "t1p_r",         
    "polotempmed_i_c": "t2p_l",           
    "polotempmed_d_c": "t2p_r",	
    "cinguant_i_c": "acin_l",
    "cinguant_d_c": "acin_r",
    "cingumed_i_c": "mcin_l",
    "cingumed_d_c": "mcin_r",
    "cingupost_i_c": "pcin_l",
    "cingupost_d_c": "pcin_r",
    "hipocampo_i_c": "hip_l",
    "hipocampo_d_c": "hip_r",
    "parahipocampo_i_c": "phip_l",
    "parahipocampo_d_c": "phip_r",	
    "insula_i_c": "in_l",
    "insula_d_c": "in_r",
	#Subcortical gray nuclei
    "amigdala_i_c": "amyg_l",
    "amigdala_d_c": "amyg_r",  
    "caudado_i_c": "cau_l",
    "caudado_d_c": "cau_r",
    "putamen_i_c": "put_l",
    "putamen_d_c": "put_r",
    "palido_i_c": "pal_l",                            
    "palido_d_c": "pal_r",                             
    "talamo_i_c": "tha_l",
    "talamo_d_c": "tha_r"
    }
brodmann_quantitative_dict = {
    "ID": "id",
    "brodmann_1": "b1",
    "brodmann_2":"b2",
    "brodmann_3":"b3",
    "brodmann_4":"b4",
    "brodmann_5":"b5",
    "brodmann_6":"b6",
    "brodmann_7":"b7",
    "brodmann_8":"b8",
    "brodmann_9":"b9",
    "brodmann_10":"b10",
    "brodmann_11":"b11",
    "brodmann_12":"b12",
    "brodmann_13":"b13",
    "brodmann_14":"b14",
    "brodmann_15":"b15",
    "brodmann_16":"b16",
    "brodmann_17":"b17",
    "brodmann_18":"b18",
    "brodmann_19":"b19",
    "brodmann_20":"b20",
    "brodmann_21":"b21",
    "brodmann_22":"b22",
    "brodmann_23":"b23",
    "brodmann_24":"b24",
    "brodmann_25":"b25",
    "brodmann_26":"b26",
    "brodmann_27":"b27",
    "brodmann_28":"b28",
    "brodmann_29":"b29",
    "brodmann_30":"b30",
    "brodmann_31":"b31",
    "brodmann_32":"b32",
    "brodmann_33":"b33",
    "brodmann_34":"b34",
    "brodmann_35":"b35",
    "brodmann_36":"b36",
    "brodmann_37":"b37",
    "brodmann_38":"b38",
    "brodmann_39":"b39",
    "brodmann_40":"b40",
    "brodmann_41":"b41",
    "brodmann_42":"b42",
    "brodmann_43":"b43",
    "brodmann_44":"b44",
    "brodmann_45":"b45",
    "brodmann_46":"b46",
    "brodmann_47":"b47"
    }

brodmann_qualitative_dict = {
    "ID": "id",
    "brodmann_1_c": "b1",
    "brodmann_2_c":"b2",
    "brodmann_3_c":"b3",
    "brodmann_4_c":"b4",
    "brodmann_5_c":"b5",
    "brodmann_6_c":"b6",
    "brodmann_7_c":"b7",
    "brodmann_8_c":"b8",
    "brodmann_9_c":"b9",
    "brodmann_10_c": "b10",
    "brodmann_11_c":"b11",
    "brodmann_12_c":"b12",
    "brodmann_13_c":"b13",
    "brodmann_14_c":"b14",
    "brodmann_15_c":"b15",
    "brodmann_16_c":"b16",
    "brodmann_17_c":"b17",
    "brodmann_18_c":"b18",
    "brodmann_19_c":"b19",
    "brodmann_20_c":"b20",
    "brodmann_21_c":"b21",
    "brodmann_22_c":"b22",
    "brodmann_23_c":"b23",
    "brodmann_24_c":"b24",
    "brodmann_25_c":"b25",
    "brodmann_26_c":"b26",
    "brodmann_27_c":"b27",
    "brodmann_28_c":"b28",
    "brodmann_29_c":"b29",
    "brodmann_30_c":"b30",
    "brodmann_31_c":"b31",
    "brodmann_32_c":"b32",
    "brodmann_33_c":"b33",
    "brodmann_34_c":"b34",
    "brodmann_35_c":"b35",
    "brodmann_36_c":"b36",
    "brodmann_37_c":"b37",
    "brodmann_38_c":"b38",
    "brodmann_39_c":"b39",
    "brodmann_40_c":"b40",
    "brodmann_41_c":"b41",
    "brodmann_42_c":"b42",
    "brodmann_43_c":"b43",
    "brodmann_44_c":"b44",
    "brodmann_45_c":"b45",
    "brodmann_46_c":"b46",
    "brodmann_47_c":"b47"
}